settings:
  title: 'Chjgo.com Status Page'
  url: 'https://status.chjgo.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: chjgo-com # unique identifier
    name: chjgo.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://chjgo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: ftp-chjgo-com # unique identifier
    name: ftp.chjgo.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://ftp.chjgo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: linux-chjgo-com # unique identifier
    name: linux.chjgo.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://linux.chjgo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: chat-chjgo-com # unique identifier
    name: chat.chjgo.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://chat.chjgo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: lobe-chjgo-com # unique identifier
    name: lobe.chjgo.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://lobe.chjgo.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
